# Generated by Django 3.1.1 on 2020-12-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_unit',
            field=models.CharField(choices=[('lbs', 'Pound'), ('kg', 'Kilogram')], default='lbs', max_length=3),
        ),
    ]
