# Generated by Django 3.1.1 on 2020-12-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20201222_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_lost',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='start_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_unit',
            field=models.CharField(blank=True, choices=[('lbs', 'Pound'), ('kg', 'Kilogram')], default='lbs', max_length=3),
        ),
    ]
