# Generated by Django 3.1.1 on 2020-12-22 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20201222_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
    ]
