# Generated by Django 3.1.1 on 2020-12-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20201222_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdiary',
            name='log_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fitnessdiary',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_unit',
            field=models.CharField(choices=[('lbs', 'Pound'), ('kg', 'Kilogram')], default='lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_lost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
