# Generated by Django 3.1.1 on 2020-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20201222_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_unit',
            field=models.CharField(choices=[('lbs', 'Pound'), ('kg', 'Kilogram')], default='lbs', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_lost',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
