# Generated by Django 3.1.1 on 2020-12-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_auto_20201222_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdiary',
            name='timestamp',
            field=models.DateField(blank=True),
        ),
    ]
