# Generated by Django 3.1.1 on 2020-12-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_food_brand_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
