# Generated by Django 3.1.1 on 2020-12-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_auto_20201223_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdiary',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
