# Generated by Django 3.1.1 on 2020-12-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_auto_20201227_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
    ]
