# Generated by Django 3.1.1 on 2020-12-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20201229_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
