# Generated by Django 3.1.1 on 2020-12-29 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
