# Generated by Django 3.1.1 on 2020-12-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_post_dislike_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='post_timestamp',
        ),
    ]
