# Generated by Django 3.1.1 on 2020-12-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_auto_20201230_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessdiary',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
